name: drivers_log
description: An app to help young drivers prepare for their drivers license.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  path: ^1.8.3
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
